apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "model-chart.fullname" . }}
  labels:
    app: {{ include "model-chart.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "model-chart.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "model-chart.name" . }}
    spec:
      containers:
        - name: model-container
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
