apiVersion: v1
kind: Service
metadata:
  name: {{ include "model-chart.fullname" . }}
  labels:
    app: {{ include "model-chart.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
  selector:
    app: {{ include "model-chart.name" . }}
